### ISSUE TITLE
Does it support multiple source directories ?

### ISSUE THREAD

**Issue by SeleDreams** [d2r2/go-rsync#11]
I remember reading that rsync itself does support syncing multiple directories by passing all the directories as arguments cf this answer https://unix.stackexchange.com/a/368216

that's why i was wondering if the tool supports giving multiple sources

**Comment by d2r2** [comment]
You can specify multiple sources in single profile to backup data from more than 1 source in one backup session. You just need to press + button in profile configuration to add next source (and configure it).

**Comment by d2r2** [comment]
No more questions on this topic.
