### ISSUE TITLE
Schema installation script  fails to find schema xml file

### ISSUE THREAD

**Issue by YongCho** [d2r2/go-rsync#2]
When installing gsettings schema with gs_schema_install.sh according to the README, the script fails with below error.
```
github.com/d2r2/go-rsync$ sudo ./ui/gtkui/gs_schema_install.sh
Installing gsettings schema to prefix /usr
Copying and compiling schema...
install: cannot stat 'gsettings/org.d2r2.gorsync.gschema.xml': No such file or directory
```

**Comment by d2r2** [comment]
I don't like complications, and it would be right to just go into the folder and run ./gs_schema_install.sh. But, since I give such description, let it be with the extra prefix path.

Wait a moment...

**Comment by d2r2** [comment]
As I said before, we will not complicate the problem and modify `gs_schema_install.sh`, but just need to correct the description in README.md.

**Comment by YongCho** [comment]
No problem. Didn't know the script was being called by another script.

**Comment by d2r2** [comment]
@YongCho, in any case thanks for pointing to incorrect documentation!

I guess we need to put in README.md instead of `$ sudo ./ui/gtkui/gs_schema_install.sh` something like `$ cd ./ui/gtkui && sudo ./gs_schema_install.sh && cd ./../..`.

If you'l like, you can prepare this PR.

**Comment by d2r2** [comment]
@YongCho, you can read about [fpm](https://github.com/jordansissel/fpm) - this cool utility is used to generate Linux packages for various Linux distributives. So, I call fpm from `create_distrib_packages_with_fpm.sh`. Advantage of this utility - it can create installation package for almost any Linux distributive.
